admins: []
forwards:
- source: -1001258910382
  dest:
  - -1001155537619
  offset: 47108
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 10.0
plugins:
  filter:
    files:
      whitelist:
      - document
      - video
      - video_note
